### ISSUE TITLE
Image is out of date and there is seemingly no way to update

### ISSUE THREAD

**Issue by LinusOP** [CodelyTV/n8n-codely-custom-image#3]
Hello, first of all I feel it's great that you provide this image for those of us who run N8N in a container!

However, I just noticed the latest version of this image is `0.228.2` but the latest version of N8N is `0.233.1`.
There doesn't seem to be a way for me to run the github action as described in the README.

Is this intentional or is the README aimed at how maintainers should run the action and I am just misunderstanding?
Lastly, could we please have it triggered? 😄 

Cheers!

**Comment by JavierCane** [comment]
Hi @LinusOP, sorry for the late response. We updated the image last week. Hope it helps!
